import Head from "next/head";
import styles from "../styles/Home.module.css";
import { MuiAppBar } from "../components/MuiAppBar";
import { MuiDrawer } from "../components/MuiDrawer";
import { useState } from "react";

const Home = () => {
    const [isDrawerOpen, setIsDrawerOpen] = useState(false);
    return (
        <div className={styles.container}>
            <Head>
                <title>team 4</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MuiAppBar setIsDrawerOpen={setIsDrawerOpen} />
            <MuiDrawer
                setIsDrawerOpen={setIsDrawerOpen}
                isDrawerOpen={isDrawerOpen}
            />
        </div>
    );
};
export default Home;
